### PR TITLE
feat: card variants

### PR DESCRIPTION
**Pull request by OK1ez**
adds artist, folder and album cards variants

### CODE REVIEW

**Comment by OK1ez** [comment]
image

**Comment by RichardKanshen** [comment]
One slight issue with this might be the way I am currently working on the playlists feature. I will check and see what we can do.

**Comment by HitBox38** [comment]
Yeah I'm also working on the artist avatar feature.

**Comment by BostonRohan** [comment]
Would it be easier to merge this first so then everyone can resolve changes in their branches?

**Comment by RichardKanshen** [comment]
> Would it be easier to merge this first so then everyone can resolve changes in their branches?

yup, that was the suggestion

**Review by BostonRohan — APPROVED** [review]

**Pull request merged**
